// apps/news-site/news-site-next/src/components/article/article-image.jsx
import Image from "next/image";
import ArticleText from "./article-text";
import ArticleTag from "./article-tag";

import styles from "news-site-css/dist/article.module.css";

export default function ArticleImage({ image, imageClass, meta }) {
    if (!image)
        return null;

    return (
        <>
            <div className={imageClass}>
                <Image className={styles["article-image"]} src={`/${image.src}`} width={image.width} height={image.height} alt={image.alt} />
                <ArticleTag tag={meta?.tag} />
            </div>
            <ArticleText textClass={styles["article-image-captions"]} text={meta?.captions} />
        </>
    );
}

// apps/news-site/news-site-nuxt/components/atoms/ArticleImage.vue
<script setup>
import styles from "news-site-css/dist/article.module.css";

const { image, imageClass, meta } = defineProps({
    image: Object,
    imageClass: String,
    meta: Object,
});
</script>

<template>
  <div
    v-if="image"
    :class="imageClass"
  >
    <img
      :class="styles['article-image']"
      :src="image.src"
      :width="image.width"
      :height="image.height"
      :alt="image.alt"
    >
    <ArticleTag :tag="meta?.tag" />
  </div>
  <ArticleText
    :text-class="styles['article-image-captions']"
    :text="meta?.captions"
  />
</template>
