// apps/news-site/news-site-next/src/components/sitemap/sitemap.jsx
import classNames from "classnames";
import { NavLink } from "react-router-dom";
import { HashLink } from "react-router-hash-link";

import { useDataContext } from "@/context/data-context";

import styles from "news-site-css/dist/sitemap.module.css";

export default function Sitemap() {
    const { content } = useDataContext();

    const keys = Object.keys(content);
    const navItems = keys.reduce((result, key) => {
        result.push(key);
        return result;
    }, []);

    return (
        <div className={styles.sitemap}>
            <ul className={styles["sitemap-list"]}>
                {navItems.map((key) =>
                    <li className={styles["sitemap-item"]} key={`sitemap-page-${content[key].name}`}>
                        <NavLink to={content[key].url} className={({ isActive }) => classNames({ [styles.active]: isActive })}>
                            <h4 className={styles["sitemap-header"]}>{content[key].name}</h4>
                        </NavLink>
                        <ul className={styles["sitemap-sublist"]}>
                            {content[key].sections.map((section) =>
                                <li className={styles["sitemap-subitem"]} key={`sitemap-section${section.id}`}>
                                    <HashLink to={`${content[key].url}#${section.id}`}>{section.name}</HashLink>
                                </li>
                            )}
                        </ul>
                    </li>
                )}
            </ul>
        </div>
    );
}

// apps/news-site/news-site-nuxt/components/atoms/Sitemap.vue
<script setup>
import { inject } from "vue";
import styles from "news-site-css/dist/sitemap.module.css";

defineProps({
    onClick: Function
});

const { content } = inject("data");

const keys = Object.keys(content);
const navItems = keys.reduce(
    (result, key) => {
        result.push(key);
        return result;
    },
    []
);
</script>

<template>
  <div :class="styles.sitemap">
    <ul :class="styles['sitemap-list']">
      <li
        v-for="key in navItems"
        :key="`sitemap-page-${content[key].name}`"
        :class="styles['sitemap-item']"
      >
        <NuxtLink
          :to="content[key].url"
          :active-class="styles['active']"
        >
          <h4 :class="styles['sitemap-header']">
            {{ content[key].name }}
          </h4>
        </NuxtLink>
        <ul :class="styles['sitemap-sublist']">
          <li
            v-for="section in content[key].sections"
            :key="`sitemap-section${section.id}`"
            :class="styles['sitemap-subitem']"
          >
            <NuxtLink :to="`${content[key].url}#${section.id}`">
              {{ section.name }}
            </NuxtLink>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</template>
