// apps/news-site/news-site-next/src/partials/navigation/navigation.jsx
import { useState } from "react";
import { createPortal } from "react-dom";
import classNames from "classnames";

import Sidebar from "@/components/sidebar/sidebar";
import Modal from "@/components/modal/modal";
import Navbar from "@/components/navbar/navbar";

import { useDataContext } from "@/context/data-context";

import navStyles from "news-site-css/dist/nav.module.css";
import buttonStyles from "news-site-css/dist/button.module.css";

export default function Navigation() {
    const [showSidebar, setShowSidebar] = useState(false);
    const [showLogin, setShowLogin] = useState(false);
    const { buttons } = useDataContext();

    function openSidebar() {
        setShowSidebar(true);
    }

    function closeSidebar() {
        setShowSidebar(false);
    }

    function openLogin() {
        setShowLogin(true);
    }

    function closeLogin() {
        setShowLogin(false);
    }

    return (
        <>
            <nav className={navStyles["page-navigation"]} aria-label="main menu">
                <div className={navStyles["page-navigation-row"]}>
                    <div className={navStyles["page-navigation-column-left"]}>
                        <Navbar callback={openSidebar} />
                    </div>
                    <div className={navStyles["page-navigation-column-right"]}>
                        <button id="login-button" className={classNames(buttonStyles.button, buttonStyles["secondary-button"], navStyles["nav-button"])} onClick={openLogin}>
                            {buttons.login.label}
                        </button>
                    </div>
                </div>
            </nav>
            {showSidebar ? createPortal(<Sidebar onClose={closeSidebar} />, document.getElementById("sitemap-container")) : null}
            {showLogin ? createPortal(<Modal onClose={closeLogin} />, document.getElementById("login-container")) : null}
        </>
    );
}

// apps/news-site/news-site-nuxt/components/molecules/Navigation.vue
<script setup>
import { inject, ref } from "vue";
import navStyles from "news-site-css/dist/nav.module.css";
import buttonStyles from "news-site-css/dist/button.module.css";

const { buttons } = inject("data");
const showSidebar = ref(false);
const showLogin = ref(false);

function openLogin() {
    showLogin.value = true;
}

function closeLogin() {
    showLogin.value = false;
}

function openSidebar() {
    showSidebar.value = true;
}

function closeSidebar() {
    showSidebar.value = false;
}
</script>

<template>
  <nav
    :class="navStyles['page-navigation']"
    aria-label="main menu"
  >
    <div :class="navStyles['page-navigation-row']">
      <div :class="navStyles['page-navigation-column-left']">
        <Navbar :callback="openSidebar" />
      </div>
      <div :class="navStyles['page-navigation-column-right']">
        <button
          id="login-button"
          :class="[buttonStyles.button, buttonStyles['secondary-button'], navStyles['nav-button']]"
          @click="openLogin"
        >
          {{ buttons.login.label }}
        </button>
      </div>
    </div>
  </nav>
  <Teleport to="body">
    <Sidebar
      v-show="showSidebar"
      :on-close="closeSidebar"
    />
  </Teleport>
  <Teleport to="body">
    <Modal
      v-show="showLogin"
      :on-close="closeLogin"
    />
  </Teleport>
</template>
