// apps/news-site/news-site-nuxt/components/atoms/NavlistItem.vue
<script setup>
import styles from "news-site-css/dist/navbar.module.css";

const { label, url, callback, id } = defineProps({
    label: String,
    url: String,
    callback: Function,
    id: String,
});
</script>

<template>
  <NuxtLink
    :id="id"
    :active-class="styles['active']"
    :to="url"
    @click="callback"
  >
    {{ label }}
  </NuxtLink>
</template>

// apps/news-site/news-site-next/src/components/navlist/navlist-item.jsx
import { NavLink } from "react-router-dom";
import classNames from "classnames";

import styles from "news-site-css/dist/navbar.module.css";

export default function NavListItem({ id, label, url, callback, itemClass, isActive }) {
    return (
        <li className={classNames(styles["navbar-item"], itemClass)} onClick={callback}>
            <NavLink to={url} id={id} className={({ isActive }) => classNames({ [styles.active]: isActive })}>
                {label}
            </NavLink>
        </li>
    );
}
