// apps/news-site/news-site-nuxt/components/organisms/Layout.vue
<script setup>
import { ref, inject, onMounted, watch } from "vue";
import { useRoute } from "#imports";
import styles from "news-site-css/dist/layout.module.css";

const showMessage = ref(false);
const route = useRoute();

const { content, links } = inject("data");

function updateShowMessage() {
    showMessage.value = content[route.name]?.message ? true : false;
}

onMounted(updateShowMessage);
watch(() => route.path, updateShowMessage);

const closeMessage = () => {
    showMessage.value = false;
};
</script>

<template>
  <NuxtLink
    :to="`${route.path}#content`"
    class="skip-link"
  >
    {{ links.a11y.skip.label }}
  </NuxtLink>
  <div
    id="page"
    :class="styles.page"
  >
    <Header />
    <Navigation />
    <Message
      v-if="content[route.name]?.message"
      v-show="showMessage"
      :on-close="closeMessage"
      :message="content[route.name]?.message"
    />
    <Main>
      <slot />
    </Main>
    <Footer />
  </div>
</template>

// apps/news-site/news-site-next/src/partials/layout/layout.jsx
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { HashLink } from "react-router-hash-link";

import Header from "../header/header";
import Navigation from "../navigation/navigation";
import Main from "../main/main";
import Footer from "../footer/footer";

import { useDataContext } from "@/context/data-context";
import { Message } from "@/components/message/message";

import styles from "news-site-css/dist/layout.module.css";
import { useRouter } from "next/router";

export default function Layout({ children, id }) {
    const [showMessage, setShowMessage] = useState(false);
    const { content, links } = useDataContext();
    const router = useRouter();

    function handleRouteChangeComplete(url) {
        window.dispatchEvent(new CustomEvent("route-change-complete", { detail: { url } }));
    }

    useEffect(() => {
        router.events.on("routeChangeComplete", handleRouteChangeComplete);

        return () => router.events.off("routeChangeComplete", handleRouteChangeComplete);
    }, []);

    useEffect(() => {
        setShowMessage(content[id].message);
    }, [content, id]);

    const pageRef = useRef(null);
    const pathname = usePathname();

    function closeMessage() {
        setShowMessage(false);
    }

    return (
        <>
            <HashLink to={`${pathname}#content`} className="skip-link">
                {links.a11y.skip.label}
            </HashLink>
            <div className={styles.page} ref={pageRef}>
                <Header />
                <Navigation />
                {showMessage ? <Message message={content[id].message} onClose={closeMessage} /> : null}
                <Main>{children}</Main>
                <Footer />
            </div>
        </>
    );
}
